### ISSUE TITLE
代码部分不能显示

### ISSUE THREAD

**Issue by wenPKtalk** [it-ebooks-0/geektime-books#3]
你们都用什么软件阅读，怎么感觉好多打开代码部分显示不出来

**Comment by MrHuiwei** [comment]
koodo、neatreader

**Comment by ghost** [comment]
> 你们都用什么软件阅读，怎么感觉好多打开代码部分显示不出来

koodo、neatreader

**Comment by Lukasz18e1** [comment]
> 你们都用什么软件阅读，怎么感觉好多打开代码部分显示不出来
